# Generated by Django 5.0.4 on 2024-04-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HallTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('exam_name', models.CharField(max_length=20)),
                ('center', models.CharField(max_length=20)),
                ('date_of_exam', models.DateField()),
                ('time', models.TimeField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
